import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const sequelSans = localFont({
  src: [
    { path: "./fonts/SequelSansHeadlineRegular.woff2", weight: "400" },
    { path: "./fonts/SequelSansHeadlineSemi.woff2", weight: "600" },
  ],
  variable: "--font-sequel-sans",
});

const recoleta = localFont({
  src: [{ path: "./fonts/Recoleta-400.woff2", weight: "400" }],
  variable: "--font-recoleta",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${sequelSans.variable} ${recoleta.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
